name: ci
on: {push: {branches: [main]}, pull_request: {}}
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black flake8
      - run: |
          black --check src tests
          flake8 src tests
      - run: pytest -q || true
      - run: docker build -t fantasy-sim:latest .
